version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram_bot
    restart: always  # Изменено с unless-stopped на always для автоматического перезапуска
    env_file:
      - .env
    volumes:
      - ./bot_database.db:/app/bot_database.db
      - ./assets:/app/assets
    environment:
      - PYTHONUNBUFFERED=1
    # Настройки здоровья контейнера (опционально)
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep '[p]ython main.py' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s