version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./bot_database.db:/app/bot_database.db
      - ./assets:/app/assets
    environment:
      - PYTHONUNBUFFERED=1